### ISSUE TITLE
To-do list for version 0.14

### ISSUE THREAD

**Issue by eeeeeta** [eeeeeta/glitch-in-the-matrix#5]
- [ ] relax error handling on MatrixRequestable to accept anything coerceable into failure::Error
- [ ] maybe un-specialcase the hyper errors while we're at it
- [ ] go over and fix missing docs
- [ ] fix README
- [ ] write at least one nice example
- [ ] clarify how cloning a MatrixClient works, and perhaps special-case this for ASes
